[book]
authors = ["Jorel Ali"]
language = "en"
multilingual = false
src = "src"
title = "Sample"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[build]
build-dir = "./docs"